/**
 * ESTE É O SEU BANCO DE DADOS DE DISCIPLINAS E TEMAS.
 * * IMPORTANTE:
 * 1. A "chave" da disciplina (ex: "direito-penal") deve ser o nome exato da pasta em /data/.
 * 2. O 'temas' é agora um ARRAY apenas com os nomes dos arquivos .json (sem a extensão .json).
 *
 * Ex: A entrada "A_norma_penal" irá carregar o arquivo:
 * /data/direito-penal/A_norma_penal.json
 * ... e será exibido no menu como "A norma penal".
 */
const dbDisciplinas = {
    "direitocivil": {
        nome: "Direito Civil",
        temas: [
            "Aceitação_e_Renúncia_da_Herança_Herança_Jacente_e_Vacante",
            "Adimplemento_Modalidades_de_Pagamento_e_Extinção_das_Obrigações",
            "Adoção_no_Direito_de_Família",
            "Aspectos_Gerais_do_Direito_das_Sucessões_–_Momento_Espécies_Lugar_Herança_e_Representação",
            "Aspectos_Introdutórios",
            "Ato_Jurídico_Fato_Jurídico_e_Teoria_Geral_do_Negócio_Jurídico",
            "Atos_Ilícitos",
            "Atos_Unilaterais_Pagamento_Indevido_e_Enriquecimento_sem_Causa",
            "Atos_Unilaterais_Promessa_de_Recompensa_e_Gestão_de_Negócios",
            "Ausência",
            "Casamento_no_Direito_de_Família",
            "Classificação_dos_Contratos",
            "Cláusulas_Especiais_de_Compra_e_Venda",
            "Compra_e_Venda",
            "Condomínio",
            "Condomínio_Edilício",
            "Constituição_da_Relação_Contratual_-_sujeitos_forma_e_objeto",
            "Contrato_Aleatório_e_Contrato_Preliminar",
            "Contratos_Atípicos",
            "Contratos_em_Espécie",
            "Contratos_em_Geral",
            "Corretagem_Transporte_Seguro_Constituição_de_Renda_Jogo_e_Aposta_e_Fiança",
            "Defeitos_do_Negócio_Jurídico",
            "Depósito_Mandato_Comissão_Agência_e_Distribuição",
            "Desapropriação",
            "Direito_das_Coisas_Direitos_Reais",
            "Direito_das_Obrigações",
            "Direito_das_Sucessões",
            "Direito_de_Família",
            "Direito_de_Laje",
            "Direito_de_Vizinhança",
            "Direitos_Reais_de_Garantia_-_Penhor_Anticrese_e_Hipoteca",
            "Domicílio_e_Bens",
            "Efeitos_Tutela_Transmissão_e_Perda_da_Posse",
            "Efeitos_perante_Terceiros_Estipulação_em_Favor_de_Terceiros_Contratos_com_Pessoa_a_Declarar_e_Promes",
            "Elementos_Essenciais_–_Conduta_Nexo_Causal_Culpa_e_Dano",
            "Empréstimo_Comodato_e_Mútuo",
            "Enfiteuse_e_Superfície",
            "Excludentes_da_Responsabilidade_Civil",
            "Extinção_cláusula_resolutiva_onerosidade_excessiva_e_exceção_de_contrato_não_cumprido",
            "Formação_dos_Contratos",
            "Inadimplemento_das_Obrigações",
            "Indenização_-_Liquidação_do_Dano",
            "Inventário_e_Partilha",
            "Lei_de_Introdução_às_Normas_do_Direito_Brasileiro_(LINDB)",
            "Locação_de_Coisas",
            "Modalidades_da_Responsabilidade_Civil",
            "Modalidades_de_Obrigações",
            "Modos_de_Aquisição_da_Propriedade_Imóvel",
            "Modos_de_Aquisição_da_Propriedade_Móvel",
            "Modos_de_Perda_da_Propriedade",
            "Multipropriedade_Imobiliária",
            "Noções_Fundamentais_de_Direitos_Reais",
            "Noções_e_Princípios_do_Direito_Contratual",
            "Obrigação_Alimentar_no_Direito_Civil",
            "Parentesco",
            "Parte_Geral",
            "Personalidade_Pessoa_Natural_e_Capacidade",
            "Pessoa_Jurídica",
            "Poder_Familiar",
            "Posse_-_Teoria_Classificação_e_Aquisição",
            "Preferências_e_Privilégios_Creditórios",
            "Prescrição_e_Decadência",
            "Prestação_de_Serviços_e_Empreitada",
            "Princípios_Gerais_de_Direito_Civil",
            "Propriedade",
            "Propriedade_Resolúvel_e_Propriedade_Fiduciária",
            "Prova",
            "Regime_de_Bens_e_Outros_Direitos_Patrimoniais_nas_Relações_Familiares",
            "Representação",
            "Responsabilidade_Civil_-_Teorias_Espécies_e_Pressupostos",
            "Responsabilidade_civil",
            "Sem_Subcategoria",
            "Servidões",
            "Sociedade_Parceria_Arrendamento_Rural_Leasing_Franquia_Facturing_e_Direitos_Autorais",
            "Sucessão_Legítima_–_Ordem_de_Vocação_Hereditária",
            "Sucessão_Testamentária_-_Testamento_Codicilo_e_Legado",
            "Teoria_Geral_das_Obrigações",
            "Teoria_das_Nulidades_Causas_de_Nulidade_e_de_Anulabilidade",
            "Transação_e_Compromisso",
            "Transmissão_das_Obrigações",
            "Troca_ou_Permuta_Contrato_Estimatório_e_Doação",
            "Tutela_e_Curatela",
            "União_Estável",
            "Uso_e_Habitação",
            "Usucapião",
            "Usufruto",
            "Vícios_Redibitórios_e_Evicção"
        ]
    },
    "portugues": {
        nome: "Português",
        temas: [
             // Adicione os nomes dos arquivos de português aqui
        ]
    }
};
